# **Aula 10** - Biblioteca NumPy

07-10-2026

## **Importando a Biblioteca**

In [ ]:
# Importanto a biblioteca
import numpy as np

## **Criando Tensores (ndarray)**

A função array do NumPy, recebe uma lista de Python e transforma em um array NumPy.

In [ ]:
# Criando um tensor (n-darray)
tensor = np.array ([10,20,30,40,50])

print(tensor)

[10 20 30 40 50]


## **Tipo do tensor**

Como saber e especificar o tipo de dado representado no tensor

In [ ]:
# Como saber o tipo criado
print (tensor.dtype)

# Especificando o tipo ao criar o tensor
tensor = np.array([10,20,30,40,50], dtype='float32')
print (tensor.dtype)

int64
float32


## **Acesso aos Elementos (Indexação)**

O acesso aos elementos de um tensor pode ser feito utilizando colchetes e o
índice do elemento. Similar a listas.

In [ ]:
print (tensor[1])

20.0


## **Tensor Shape**

Os tensores NumPy também possuem um atributo chamado shape que indica a
forma do tensor.

O método reshape permite alterar o formato do tensor.

In [ ]:
# Método Shape
# Criando o tensor unidimensional que corresponde a um vetor.
tensor = np.array([10,20,30,40,50,60])
print (tensor.shape)

# Alterando o formato
tensor.shape = (2,3)
print (tensor)

# reshape permite o uso de -1 na dimensão (determina automaticamento o número de elementos)
tensor = np.array([10,20,30,40,50,60]).reshape(3,-1)
print (tensor)

(6,)
[[10 20 30]
 [40 50 60]]
[[10 20]
 [30 40]
 [50 60]]


## **Funções (zeros, ones, diag)**

Funções que facilitam a criação
de tensores.

In [ ]:
# Funções Convenientes
# Zeros - Cria o tensor preechido com zeros
Z = np. zeros ( (4,4))
print('Z = \n', Z)
print(Z.dtype)

# Ones - Cria o tensor preechido com uns
U = np.ones((4,4), dtype='int64')
print('U = \n', U)
print(U.dtype)

# Diag - Preenche a diagonal com os valores passados
D = np.diag([7, 7, 7, 7])
print('D = \n', D)
print(D.dtype)

Z = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
U = 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64
D = 
 [[7 0 0 0]
 [0 7 0 0]
 [0 0 7 0]
 [0 0 0 7]]
int64


## **Métodos Úteis (arange, linspace)**

Métodos que facilitam a criação de tensores

In [ ]:
#método arange
# forma de uso: np.arange([start, ]stop, [step, ], dtype=None)
a = np.arange(0, 5, 0.5)
print("a =", a)

#método linspace
# forma de uso: np.linspace(start = 0, stop = 100, num = 5)
1 == np.linspace(0, 5, 10)
print("1 =", 1)

a = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
1 = 1


## **Criando Tensor e Modificando**

In [ ]:
# Cria um tensor com valores de 1 a 50
# Modifica o formato para 2,5,5
tensor = np.array(range(50)).reshape(2,5,-1)
print(f'Tensor Original: {tensor}')

# gera uma cópia do tensor no formato vetor unidimensional
print(f'Tensor Modificado (flat): {tensor.flatten()}')

# Transformando em vetor unidimensional usando shape
#tensor.shape = (1,-1)
#print(f'Tensor Modificado2 (flat): {tensor}')

# Atributo flat retorna uma lista iteravel do tensor
tensor_iter = tensor.flat
for i in tensor_iter:
  print(f' {i}')

Tensor Original: [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
Tensor Modificado (flat): [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31
 32
 33
 34
 35
 36
 37
 38
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49


## **Operações sobre Tensores**

### **Multiplicação por um escalar**

In [ ]:
#Multiplicação de um escalar por
# forma de uso: np.arange([start, ]stop, [step, ], dtype=None)
vetor = np.arange(0, 10, 2)
print(f'Vetor: { vetor }')

# Lendo o escalar
escalar = int(input("Valor do Escalar: "))

vetor_escalado = vetor * escalar

print(f'Vetor Escalado: { vetor_escalado }')

Vetor: [0 2 4 6 8]
Valor do Escalar: 1
Vetor Escalado: [0 2 4 6 8]


### **Multiplicação de Matrizes**

Sempre que possível use os métodos da biblioteca pois são mais rápidos.

In [ ]:
# Multiplicação de Matrizes
# cria uma matriz 2,2 com uns
a = np.ones((2,2), dtype=int)
print(f'Matriz A \n {a}')
# cria uma matriz 2,2 com uns e multiplica por 5
b = np.ones((2,2),dtype=int) *5
print(f'Matriz B \n {b}')

# Multiplicação das matrizes usando o método 'dot'
c = np.dot(a,b)
print(f'Matriz Resultado \n {c}')

# Multiplicação das matrizes usando '@'
d = a @ b
print(f'Matriz Resultado com @ \n {d}')

Matriz A 
 [[1 1]
 [1 1]]
Matriz B 
 [[5 5]
 [5 5]]
Matriz Resultado 
 [[10 10]
 [10 10]]
Matriz Resultado com @ 
 [[10 10]
 [10 10]]


## **Operadores lógicos**

As operações lógicas ocorrem elemento a elemento.

O resultado da operação é um tensor booleano com valores True ou False.

In [ ]:
# Operadores lógicos
# Array bidimensional 4x4 com numeros aleatórios inteiros entre 1 e 100
m = np.random.randint(1,101,size=(4,4))
print(f'Matriz Gerada \n {m}')

# Cria matriz lógica, True nos locais dos valores maiores que 50
ml = m >50
print(f'Matriz Logica \n {ml}')

# Zera os valores da matriz original onde os valores eram menores que 50
m[m <50]=0
print(f'Matriz Zerada menores que 50 \n {m}')

Matriz Gerada 
 [[59 19 88 93]
 [42 93  6 78]
 [ 8 25  3 79]
 [83 60  2 98]]
Matriz Logica 
 [[ True False  True  True]
 [False  True False  True]
 [False False False  True]
 [ True  True False  True]]
Matriz Zerada menores que 50 
 [[59  0 88 93]
 [ 0 93  0 78]
 [ 0  0  0 79]
 [83 60  0 98]]
